version: "3.7"
services:
  ntfy:
    image: pdkhai/ntfy
    container_name: ntfy
    command:
      - serve
    environment:
      - TZ=UTC    # optional: Change to your desired timezone
    volumes:
      - /var/cache/ntfy:/var/cache/ntfy
    ports:
      - 3300:80
    restart: unless-stopped
    pull_policy: always

