base-url: "https://notification.bitsapi.bid"
cache-file: "/var/cache/ntfy/cache.db"
attachment-cache-dir: "/var/cache/ntfy/attachments"
auth-file: "/var/cache/ntfy/user.db"
auth-default-access: "deny-all"
enable-signup: true
enable-login: true
log-level: debug
